SRC= main.cpp PmergeMe.cpp Vector.cpp Deque.cpp
OBJ = $(SRC:.cpp=.o)
NAME = PmergeMe

CC = c++
FLAGS = -Wall -Wextra -Werror
STD = -std=c++98

all: $(NAME)

$(NAME) : $(OBJ)
	$(CC) $(FLAGS) $(STD) $(OBJ) -o $(NAME)
%.o:%.cpp PmergeMe.hpp Vector.hpp Deque.hpp
	$(CC) $(FLAGS) $(STD) -c $< -o $@
clean:
	rm -rf $(OBJ)
fclean: clean
	rm -rf $(NAME)
re: fclean all